const engineConfig = {
    config_1: {
        headless: true,
        ignoreHTTPSErrors: true,
        ignoreDefaultArgs: [
            '--allow-pre-commit-input',
            '--enable-automation',
            '--enable-blink-features=IdleDetection',
            '--enable-features=NetworkServiceInProcess2',
            '--export-tagged-pdf',
            '--force-color-profile=srgb',
            '--metrics-recording-only',
            '--no-first-run',
            '--password-store=basic',
            '--use-mock-keychain',
            '--hide-scrollbars',
            '--mute-audio',
        ],
        devtools: false,
        defaultViewport: null,
        args: [
            '--start-maximized',
            '--disable-background-networking',
            '--disable-background-timer-throttling',
            '--disable-backgrounding-occluded-windows',
            '--disable-client-side-phishing-detection',
            '--disable-component-extensions-with-background-pages',
            '--disable-component-update',
            '--disable-default-apps',
            '--disable-features=IsolateOrigins,site-per-process,Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints',
            '--disable-hang-monitor',
            '--disable-ipc-flooding-protection',
            '--disable-popup-blocking',
            '--disable-prompt-on-repost',
            '--disable-renderer-backgrounding',
            '--disable-sync',
            '--disable-web-security',
            '--allow-running-insecure-content',
            '--disable-blink-features=AutomationControlled',
            '--no-sandbox',
            '--disable-infobars',
            '--disable-setuid-sandbox',
            '--mute-audio',
            '--no-zygote',
            '--no-zygote-sandbox',
            '--use-gl=swiftshader',
            '--no-xshm',
            '--hide-scrollbars',
            '--no-first-run',
            '--no-default-browser-check',
            '--disable-dev-shm-usage',
            '--enable-webgl',
            '--disable-gpu-sandbox',
            '--disable-software-rasterizer',
            '--disable-breakpad',
            '--disable-canvas-aa',
            '--disable-2d-canvas-clip-aa',
            '--disable-gl-drawing-for-tests',
            '--enable-low-end-device-mode',
            '--disable-gpu',
            '--disable-extensions',
            '--disable-dev-tools',
            '--ignore-certificate-errors',
            '--lang=es-ES,es;q=0.9'
        ]
    }
}

module.exports = engineConfig
