version: '3.3'
services:    
    cloud-scrapy:
      image: ${IMAGE_APP}:${IMAGE_TAG}
      networks:
        - traefik-swarm
        - databases-swarm
      depends_on:
        - db
        - redis_condor
      volumes:
        - screenshots_scrapy:/files/screenshots
        - logs_scrapy:/files/logs/
        - pdfs_scrapy:/files/pdfs/ 
      environment:
         - NODE_ENV=${NODE_ENV}
      deploy:
        labels:
        - "traefik.http.routers.${NAME_SERVICE_TRAEFIK}.rule=Host(`${URL_DEPLOY}`)"
        - "traefik.http.routers.${NAME_SERVICE_TRAEFIK}.entrypoints=https"
        - "traefik.http.services.${NAME_SERVICE_TRAEFIK}.loadbalancer.server.port=5000"
        - "traefik.http.routers.${NAME_SERVICE_TRAEFIK}.tls=true"
        - "traefik.docker.network=traefik-swarm"
        - "traefik.enable=true"
        placement:
          constraints:
            - "node.role == worker"
            - 'node.hostname!=invoicy-v2-clouding-pre-worker-03'
         
volumes:
  screenshots_scrapy:
    external: true
  logs_scrapy:
    external: true
  pdfs_scrapy:
    external: true

networks:
  traefik-swarm:
    external: true
  databases-swarm:
    external: true
      

  #mongo_db:
  # container_name: mongo_db_container
  #  restart: unless-stopped
  #  image: 'mongo:6.0'
  #  network_mode: bridge
  #  ports:
  #    - '27017'
  #redis:
  #  container_name: redis_container
  #  network_mode: bridge
  #  restart: unless-stopped
  #  image: redis:7.0.7-alpine
  #  expose:
  #    - '6379'