version: '3'
services:
  mongo_db:
    container_name: mongo_db_container
    restart: unless-stopped
    image: 'mongo:6.0'
    network_mode: bridge
    ports:
      - '27017'
  redis:
    container_name: redis_container
    network_mode: bridge
    restart: unless-stopped
    image: redis:7.0.7-alpine
    expose:
      - '6379'
  app:
    container_name: cloud_scrapy_container
    restart: unless-stopped
    network_mode: bridge
    expose:
      - '5000'
    ports:
      - '5000:5000'
    build: ../../../../../Nueva carpeta
    environment:
      MONGODB_URI: mongodb://mongo_db_container:27017/cloud_scrapy
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
      IMAGES_PATH: ./files/screenshots/
      LOGS_PATH: ./files/logs/
      PDF_PATH: ./files/pdfs/
      APP_HOST: http://localhost
      APP_PORT: 5000
      ANTICAPTCHA_API_KEY: YOUR_ANTICAPTCHA_API_KEY
      SECRET_TOKEN: YOUR_SECRET_TOKEN
      NODE_ENV: development
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - mongo_db
      - redis
    links:
      - mongo_db
      - redis