title = "Config Local"

[DEFAULT]
    organization_domain = 'invoicy.es'
    cloud_scrapy_server = 'http://127.0.0.1:3000'
[limits]
    browsers_contexts_allowed = 50
    time_seconds_expires = 86400
[server]
    server_url = 'http://127.0.0.1:3000'
    server_host = '127.0.0.1'
    server_port = 3000
    server_name = 'cloud-scrapy-dev'
    server_environment = 'DEV'
[mongodb]
    host = '127.0.0.1'
    port = 27017
    username = 'rootcloudscrapy'
    password = 'root.1234*'
    database = 'cloud_scrapy'
    mongodb_uri = 'mongodb://rootcloudscrapy:root.1234*@localhost:27017/cloud_scrapy?authSource=admin'
[redis]
    host = '127.0.0.1'
    port = 6379
    username = ''
    password = ''
[paths]
    images_path = './files/screenshots/'
    logs_path = './files/logs/'
    pdf_path = './files/pdfs/'
[root_user]
    username = 'root'
    email = 'root_cloud_scrapy@lucual18.es'
    name = 'root'
    password = '$2b$10$ui30FT3Qpk.PAM0XKxFmruT.Spjbb.38gVLEXPFmmHFdfrblTjSDO'
[tokens]
    ANTICAPTCHA_API_KEY = 'c77bf34c0f92dbf06b2a6ffae507d47d'
    SECRET_TOKEN = '57656c6c636f6d6520746f207363726170652074686520636c6f756473'